version: '3.3'

services:
  chsi_converter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
    volumes:
      - .:/app
